name: Main Workflow

on:
   workflow_dispatch

jobs:
  setup-java-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Java Setup and Info Workflow
      uses: ./.github/workflows/java-setup.yml

  job2:
    runs-on: ubuntu-latest
    needs: setup-java-and-run
    steps:
     - run: |
        echo "Cache found: ${{ needs.setup-java-and-run.outputs.cache }}"
