name: Java Configuration

on: workflow_dispatch

jobs:
  setup-java:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.show-config.outputs.path }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      id: setup-java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Show Java version and path
      id: show-config
      run: |
        echo "path=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_OUTPUT
